apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opa-gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: gatekeeper
      version: 3.15.0
      sourceRef:
        kind: HelmRepository
        name: opa-gatekeeper
        namespace: flux-system