apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 10m0s
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.109.0
      sourceRef:
        kind: HelmRepository
        name: otel-collector
        namespace: flux-system
  values:
    mode: "deployment"
    namespaceOverride: "monitoring"
    presets:
      kubernetesAttributes:
        enabled: true
        extractAllPodLabels: true
        extractAllPodAnnotations: true 
    image:
      # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
      repository: otel/opentelemetry-collector-k8s
      pullPolicy: IfNotPresent

    # OpenTelemetry Collector executable
    command:
      name: "otelcol-k8s"

    config:
      exporters:
        debug:
          verbosity: normal
        otlphttp:
          endpoint:  "http://grafana-tempo-distributor.monitoring.svc.cluster.local:4318"
          tls:
            insecure: true
      extensions:
        # The health_check extension is mandatory for this chart.
        # Without the health_check extension the collector will fail the readiness and liveliness probes.
        # The health_check extension can be modified, but should never be removed.
        health_check:
          endpoint: ${env:MY_POD_IP}:13133
      processors:
        batch: {}
        # Default memory limiter configuration for the collector based on k8s resource limits.
        memory_limiter:
          # check_interval is the time between measurements of memory usage.
          check_interval: 5s
          # By default limit_mib is set to 80% of ".Values.resources.limits.memory"
          limit_percentage: 80
          # By default spike_limit_mib is set to 25% of ".Values.resources.limits.memory"
          spike_limit_percentage: 25
      receivers:
        otlp:
          protocols:
            http:
              endpoint: ${env:MY_POD_IP}:4318
      service:
        pipelines:
          traces:
            receivers:
              - otlp
            exporters: 
              - otlphttp