apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces.yaml
- helm-nginx-ingress.yaml
- ebs-storage-class.yaml
- helm-prometheus.yaml
- helm-cert-manager.yaml
- helm-secrets-store-csi-driver.yaml
- helm-secrets-provider-aws.yaml
- helm-fluent-bit.yaml
- helm-otel-collector.yaml
- helm-istio.yaml
- helm-grafana-tempo.yaml
