apiVersion: v1
kind: Namespace
metadata:
  name: develop
  labels:
    project: smart-cash

---

apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    ingress: nginx
---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system

---

apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
