apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-expenses
  labels:
    app: expenses
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: expenses
  template:
    metadata:
      labels:
        app: expenses
        tier: backend
    spec:
      serviceAccountName: sa-expenses-service
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10003
        runAsGroup: 30001
      containers:
      - name: expenses-container
        image: service-image
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "50Mi"   ###### VALIDATE THESE WERE RANDOM NUMBERS TO TEST
          limits:
            memory: "100Mi"  ###### VALIDATE THESE WERE RANDOM NUMBERS TO TEST
        ports:
        - containerPort: 8282
        livenessProbe:
          httpGet:
            port: 8282  
            path: /expenses/health  
          initialDelaySeconds: 1
          periodSeconds: 10