---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: smartcash
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: develop
  url: https://github.com/danielrive/smart-cash

