apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The namespace is unique to the node, Ericsson would be just 'node'. Other customers should follow the naming convention node-customer
namespace: develop
resources:
- deployment.yaml
- service.yaml