apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
spec:
  template:
    spec:
      containers:
      - name: user-container
        env:
        - name: DYNAMODB_USER_TABLE
          value: user-table
        - name: AWS_REGION
          value: us-west-2