apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: user
spec:
  image: 658299583140.dkr.ecr.us-west-2.amazonaws.com/user-service-smart-cash
  interval: 5m0s
  timeout: 1m0s
  provider: aws

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: user
spec:
  imageRepositoryRef:
    name: user
  filterTags:
    pattern: '^develop-(?P<timestamp>\d+)$'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: img-upd-user
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@smartcash.com
        name: fluxcdbot
    push:
      branch: develop
  update:
    path: services/user-service/overlays/develop/kustomization.yaml