resources:
  - ../../base
namespace: develop
images:
  - name: user-image
    newName: 658299583140.dkr.ecr.us-west-2.amazonaws.com/user-service-smart-cash
    newTag: develop-b4d62e
patches:
  - path: patch-service-account.yaml
