apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-expenses
spec:
  template:
    spec:
      containers:
      - name: expenses-container
        env:
        - name: DYNAMODB_EXPENSES_TABLE
          value: expenses-table
        - name: AWS_REGION
          value: us-west-2