apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bank
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      serviceAccountName: sa-bank-service
      containers:
      - name: bank-container
        image: service-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8282
        livenessProbe:
          httpGet:
            port: 8282  
            path: /health  
          initialDelaySeconds: 1
          periodSeconds: 10