apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: sa-user-service
      containers:
      - name: user-service-container
        image: service-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8182
        livenessProbe:
          httpGet:
            port: 8181  
            path: /health  
          initialDelaySeconds: 5
          periodSeconds: 10
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Container started"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Container stopping"]