apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: danielrive-letsencrypt2
    kind: ClusterIssuer
  commonName: "danielrive.site"
  dnsNames:
  - "danielrive.site"
  - "monitoring.develop.smartcash.danielrive.site"

--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: develop
spec:
  secretName: frontend-tls
  issuerRef:
    name: danielrive-letsencrypt2
    kind: ClusterIssuer
  commonName: "danielrive.site"
  dnsNames:
  - "danielrive.site"
  - "develop.smartcash.danielrive.site"