apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: danielrive-letsencrypt2
spec:
  acme:
    email: notreply@rootdr.info
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: danielrive-issuer-acme
    solvers:
    - selector:
        dnsZones:
          - danielrive.site
      dns01:
        route53:
          region: us-west-2