apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jwt-secret
  namespace: develop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "smart-cash/jwt-secret/develop"
        objectType: "secretsmanager"
        jmesPath:
          - path: secret
            objectAlias: secret
    usePodIdentity: "true"
